
*******2018-06-25 08:05:47.617381*************
 本页面无数据:http://xm.58.com/ershoufang/pn4/?key=%E6%96%B0%E8%8E%B2%E8%8A%B1%E6%96%B0%E9%BE%99%E5%B1%B1%E8%8A%B1%E5%9B%AD%E4%B8%80%E6%9C%9F. 

*******2018-06-25 08:08:27.563529*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E7%A6%8F%E6%B4%A5%E5%A4%A7%E8%A1%97%EF%BC%88%E5%87%A4%E5%B1%BF%E8%B7%AF36-74%E5%8F%B7%EF%BC%89/. 

*******2018-06-25 08:09:24.383779*************
 本页面无数据:http://www.917.com/sell/?k=坑内路13-18号小区. 

*******2018-06-25 08:11:42.728692*************
 本页面无数据:http://www.917.com/sell/?k=石亭路21-25号. 

*******2018-06-25 08:13:00.487139*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E5%B0%86%E5%86%9B%E7%A5%A0%E8%B7%AF132-137%E5%8F%B7/. 

*******2018-06-25 08:13:54.872250*************
 本页面无数据:http://www.917.com/sell/?k=华昌路7-61小区. 

               *******newFunc*******,error record by @mylog on 2018-06-25 08:14:57.581837*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-06-25 08:16:48.689192*************
 本页面无数据:http://www.917.com/sell/?k=学林雅苑(金房东）. 

*******2018-06-25 08:17:55.768028*************
 本页面无数据:http://www.917.com/sell/?k=龙华大厦(南湖花园）. 

               *******newFunc*******,error record by @mylog on 2018-06-25 08:23:06.461799*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-06-25 08:25:18.939376*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-06-25 08:27:27.414725*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E6%B9%96%E5%85%89%E8%B7%AF47-50%E4%B9%8B1%E3%80%8150%E4%B9%8B2/. 
========2018-06-25 08:30:04.760522record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-06-25 08:30:57.113714*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E7%A6%BE%E7%A5%A5%E8%A5%BF%E8%B7%AF280-284%E5%8F%B7/. 

*******2018-06-25 08:32:13.874105*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E6%B9%96%E6%BB%A8%E5%8D%97%E8%B7%AF142-144%E5%8F%B7/. 

*******2018-06-25 08:37:15.119792*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E5%85%B4%E9%9A%86%E8%B7%AF259-263/. 

*******2018-06-25 08:40:46.256213*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E7%A6%BE%E7%A5%A5%E8%A5%BF%E8%B7%AF230-232%E5%8F%B7/. 

*******2018-06-25 08:42:12.799163*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E8%A7%92%E6%BB%A8%E8%B7%AF45-57%E5%8F%B7/. 

*******2018-06-25 08:48:58.329707*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E8%B1%86%E4%BB%94%E5%B0%BE%E8%B7%AF332-336%E5%8F%B7/. 

*******2018-06-25 08:54:15.073572*************
 本页面无数据:http://xm.58.com/ershoufang/pn20/?key=%E7%BB%BF%E5%88%9B%E2%80%A2%E9%93%82%E6%82%A6%E5%BA%9C. 

*******2018-06-25 08:54:42.500512*************
 本页面无数据:http://xm.58.com/ershoufang/pn18/?key=%E7%BB%BF%E5%88%9B%E2%80%A2%E9%93%82%E6%82%A6%E5%BA%9C. 

*******2018-06-25 08:55:10.059071*************
 本页面无数据:http://xm.58.com/ershoufang/pn19/?key=%E7%BB%BF%E5%88%9B%E2%80%A2%E9%93%82%E6%82%A6%E5%BA%9C. 

*******2018-06-25 08:57:27.294425*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E6%96%87%E5%9B%AD%E8%B7%AF1-3%E5%8F%B7/. 

*******2018-06-25 09:01:02.274371*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E6%B9%96%E6%BB%A8%E4%B8%80%E9%87%8C64-67%E5%8F%B7%E9%99%A2/. 

               *******newFunc*******,error record by @mylog on 2018-06-25 09:13:52.802431*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-06-25 09:15:06.266719*************
 本页面无数据:http://xm.58.com/ershoufang/pn6/?key=%E6%96%B0%E8%8E%B2%E8%8A%B1%E6%96%B0%E9%BE%99%E5%B1%B1%E8%8A%B1%E5%9B%AD. 

*******2018-06-25 09:17:00.445516*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E7%A5%A5%E4%BA%91%E5%85%AC%E5%AF%93. 

               *******newFunc*******,error record by @mylog on 2018-06-25 09:18:21.806885*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-06-25 10:08:38.998018*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E7%A6%B9%E6%B4%B2%E4%B8%AD%E5%A4%AE%E6%B5%B7%E5%B2%B8%E4%BA%8C%E6%9C%9F%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

               *******newFunc*******,error record by @mylog on 2018-06-25 10:16:31.345845*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-06-25 10:22:20.181051*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-06-25 10:23:16.562853*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range
========2018-06-25 10:38:36.759064record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
========2018-06-25 10:41:52.768955record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
========2018-06-25 10:51:27.117734record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

               *******newFunc*******,error record by @mylog on 2018-06-25 10:54:53.553894*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range
========2018-06-25 10:58:25.805979record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-06-25 11:18:47.091895*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E4%B8%87%E7%A7%91%E5%B9%BF%E5%9C%BA%28%E5%95%86%E4%BD%8F%E6%A5%BC. 

*******2018-06-25 11:30:23.062343*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E6%BA%90%E6%88%90%E5%95%86%E4%BD%8F%E7%BB%BC%E5%90%88%E6%A5%BC. 
========2018-06-25 12:30:57.230248record by outputer 
Traceback (most recent call last):
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1021, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "G:\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 987, in _read_packet
    packet_header = self._read_bytes(4)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1029, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10054] 远程主机强迫关闭了一个现有的连接。)')
========2018-06-25 12:38:33.580350record by outputer 
Traceback (most recent call last):
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1021, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "G:\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 987, in _read_packet
    packet_header = self._read_bytes(4)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1029, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10054] 远程主机强迫关闭了一个现有的连接。)')

*******2018-06-25 12:59:11.211138*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E4%B8%87%E7%A7%91%E5%B9%BF%E5%9C%BA%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 
========2018-06-25 13:23:02.969030record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-06-25 13:29:26.725980*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E5%9B%BD%E9%99%85%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

*******2018-06-25 14:55:57.508876*************
 本页面无数据:https://xm.anjuke.com/sale/p11-rd1/?kw=%E6%9D%BE%E6%9F%8F%E5%8D%8E%E5%BA%AD&from_url=kw_final#filtersort. 

*******2018-06-25 15:25:33.132436*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E4%B8%80%E6%9D%91%E7%9B%88%E7%BF%A0%E9%87%8C%E5%AD%A6%E5%8C%BA%E6%88%BF. 

*******2018-06-25 17:39:18.434682*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E5%9B%BD%E9%99%85%E5%95%86%E4%BD%8F%E6%A5%BC. 

*******2018-06-25 17:45:21.720087*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E6%BB%A8%E6%B5%B7%E5%95%86%E4%BD%8F%E4%B8%AD%E5%BF%83. 

*******2018-06-25 18:48:26.331161*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E7%A6%B9%E5%B7%9E%E9%98%B3%E5%85%89%E8%8A%B1%E5%9F%8E%E5%AD%A6%E5%8C%BA%E6%88%BF%E7%B2%BE%E8%A3%85%E6%88%BF. 

*******2018-06-25 19:32:04.493029*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%AD%A6%E5%8C%BA%E6%88%BF%E5%8F%AF%E5%85%A5%E6%88%B7%E7%A6%B9%E5%B7%9E%E9%98%B3%E5%85%89%E8%8A%B1%E5%9F%8E. 

*******2018-06-25 20:13:55.069270*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E5%A4%A7%E5%90%8C%E5%B0%8F%E5%AD%A6%E5%AF%B9%E9%9D%A2. 

*******2018-06-25 20:16:09.014944*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%87%BA%E5%94%AE%E6%B5%B7%E8%BE%B9%E5%B0%8F%E5%8C%BA%E5%AD%A6%E5%8C%BA%E6%88%BF%E4%BB%B7%E6%A0%BC%E5%AE%9E%E6%83%A0. 

*******2018-06-25 20:39:45.386359*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%87%BA%E5%94%AE%E6%B5%85%E6%B0%B4%E6%B9%BE%E7%95%94%E5%AD%A6%E5%8C%BA%E6%88%BF. 

               *******newFunc*******,error record by @mylog on 2018-06-25 21:15:17.711589*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '95-110'

               *******newFunc*******,error record by @mylog on 2018-06-25 21:15:18.235618*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '95-110'

               *******newFunc*******,error record by @mylog on 2018-06-25 21:16:19.553651*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '95-110'

*******2018-06-25 21:25:01.088406*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%AD%A6%E5%8C%BA%E6%88%BF. 

*******2018-06-25 21:43:22.101958*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E7%A6%8F%E6%B4%A5%E5%A4%A7%E8%A1%97%E4%BA%94%E8%8A%82%E7%82%B9%E5%AD%A6%E5%8C%BA%E6%88%BF. 

*******2018-06-25 23:12:59.639002*************
 本页面无数据:https://xm.anjuke.com/sale/p11/#filtersort. 

*******2018-07-02 08:25:25.779074*************
 本页面无数据:http://www.917.com/sell/?k=坑内路13-18号小区. 

*******2018-07-02 08:30:02.756916*************
 本页面无数据:http://www.917.com/sell/?k=龙华大厦(南湖花园）. 

*******2018-07-02 08:31:52.123171*************
 本页面无数据:http://www.917.com/sell/?k=湖明路103-108号. 

*******2018-07-02 08:32:16.333556*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E7%A6%8F%E6%B4%A5%E5%A4%A7%E8%A1%97%EF%BC%88%E5%87%A4%E5%B1%BF%E8%B7%AF36-74%E5%8F%B7%EF%BC%89/. 

               *******newFunc*******,error record by @mylog on 2018-07-02 08:33:59.322447*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-07-02 08:35:17.603497*************
 本页面无数据:http://www.917.com/sell/?k=华昌路7-61小区. 

*******2018-07-02 08:36:39.066840*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E6%B9%96%E6%BB%A8%E4%B8%80%E9%87%8C64-67%E5%8F%B7%E9%99%A2/. 
========2018-07-02 08:38:36.865141record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-07-02 08:40:22.095769*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E8%A7%92%E6%BB%A8%E8%B7%AF45-57%E5%8F%B7/. 

*******2018-07-02 08:40:50.336928*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E5%B0%86%E5%86%9B%E7%A5%A0%E8%B7%AF132-137%E5%8F%B7/. 

*******2018-07-02 08:46:15.792850*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E5%85%B4%E9%9A%86%E8%B7%AF259-263/. 

*******2018-07-02 08:50:38.710563*************
 本页面无数据:http://www.917.com/sell/?k=石亭路21-25号. 

*******2018-07-02 09:06:21.442112*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E6%96%87%E5%9B%AD%E8%B7%AF1-3%E5%8F%B7/. 

*******2018-07-02 09:10:40.876871*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E7%A6%BE%E7%A5%A5%E8%A5%BF%E8%B7%AF230-232%E5%8F%B7/. 

*******2018-07-02 09:10:57.918494*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E7%A6%B9%E6%B4%B2%E4%B8%AD%E5%A4%AE%E6%B5%B7%E5%B2%B8%E4%BA%8C%E6%9C%9F%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

*******2018-07-02 09:24:44.302286*************
 本页面无数据:https://xm.ke.com/ershoufang/pg1rs%E7%A6%BE%E7%A5%A5%E8%A5%BF%E8%B7%AF280-284%E5%8F%B7/. 

               *******newFunc*******,error record by @mylog on 2018-07-02 09:31:02.865220*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 09:44:06.412861*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 09:48:33.865900*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 09:57:17.673910*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-07-02 10:04:01.200583*************
 本页面无数据:http://xm.58.com/ershoufang/pn4/?key=%E6%96%B0%E8%8E%B2%E8%8A%B1%E6%96%B0%E9%BE%99%E5%B1%B1%E8%8A%B1%E5%9B%AD%E4%B8%80%E6%9C%9F. 

               *******newFunc*******,error record by @mylog on 2018-07-02 10:19:17.974557*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 10:20:45.542945*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 10:27:48.223198*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 10:41:47.871405*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range
========2018-07-02 10:42:11.771506record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

               *******newFunc*******,error record by @mylog on 2018-07-02 10:42:24.820875*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 10:43:05.380004*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-07-02 10:45:26.535079*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range
========2018-07-02 10:45:32.784362record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-07-02 10:54:43.359740*************
 本页面无数据:http://xm.ganji.com/fang5/o111/. 

*******2018-07-02 10:55:51.413645*************
 本页面无数据:http://xm.ganji.com/fang5/o113/. 

*******2018-07-02 10:56:14.610554*************
 本页面无数据:http://xm.ganji.com/fang5/o114/. 

*******2018-07-02 10:56:40.481108*************
 本页面无数据:http://xm.ganji.com/fang5/o112/. 

               *******newFunc*******,error record by @mylog on 2018-07-02 11:05:51.589314*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range
========2018-07-02 11:07:30.799276record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
========2018-07-02 11:10:51.974677record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

               *******newFunc*******,error record by @mylog on 2018-07-02 11:16:19.084810*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-07-02 11:16:27.564927*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E5%9B%BD%E9%99%85%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

*******2018-07-02 12:06:53.628363*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E4%B8%87%E7%A7%91%E5%B9%BF%E5%9C%BA%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

*******2018-07-02 13:11:29.687919*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E5%AF%8C%E5%85%B4%E5%A4%A7%E5%8E%A6. 

*******2018-07-02 13:36:44.033534*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E6%BB%A8%E6%B5%B7%E5%95%86%E4%BD%8F%E4%B8%AD%E5%BF%83. 

*******2018-07-02 14:05:47.422969*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E6%98%A5%E6%B1%9F%E9%87%8C%2855-79%29. 

*******2018-07-02 14:29:39.035743*************
 本页面无数据:http://xm.58.com/ershoufang/pn19/?key=%E7%BB%BF%E5%88%9B%E2%80%A2%E9%93%82%E6%82%A6%E5%BA%9C. 

*******2018-07-02 14:30:13.482993*************
 本页面无数据:http://xm.58.com/ershoufang/pn17/?key=%E7%BB%BF%E5%88%9B%E2%80%A2%E9%93%82%E6%82%A6%E5%BA%9C. 

*******2018-07-02 14:32:34.468890*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E7%9F%B3%E6%B3%89%E8%B7%AF%E5%B0%8F%E5%8C%BA. 

*******2018-07-02 14:40:36.851183*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E5%9B%BD%E9%99%85%E5%95%86%E4%BD%8F%E6%A5%BC. 

*******2018-07-02 14:54:07.234366*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E5%BB%BA%E8%AE%BE%E5%A4%A7%E5%8E%A6. 

*******2018-07-02 16:37:19.073990*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E6%BA%90%E6%88%90%E5%95%86%E4%BD%8F%E7%BB%BC%E5%90%88%E6%A5%BC. 

               *******newFunc*******,error record by @mylog on 2018-07-02 18:00:21.108343*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '44-50'

               *******newFunc*******,error record by @mylog on 2018-07-02 18:00:28.178353*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '44-50'

               *******newFunc*******,error record by @mylog on 2018-07-02 18:01:07.743411*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '44-50'

*******2018-07-02 18:36:27.351478*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E7%A6%8F%E6%B4%A5%E5%A4%A7%E8%A1%97%E4%BA%94%E8%8A%82%E7%82%B9%E5%AD%A6%E5%8C%BA%E6%88%BF. 

               *******newFunc*******,error record by @mylog on 2018-07-02 18:47:45.423457*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '44-50'

               *******newFunc*******,error record by @mylog on 2018-07-02 18:47:48.453461*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '44-50'

               *******newFunc*******,error record by @mylog on 2018-07-02 18:48:58.552562*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 89, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 45, in page_parse
    new_datas = self.parse_datas(soup)
  File "E:\py3-craw\WbPage.py", line 49, in parse_datas
    d1 = self.parse_item(string)
  File "E:\py3-craw\PageParser.py", line 114, in parse_item
    parse_dict['area'] = int(round(float(re.search(r1_3, string).groups(0)[0]),0))
ValueError: could not convert string to float: '44-50'

*******2018-07-02 18:52:28.012858*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E4%B8%80%E6%9D%91%E7%9B%88%E7%BF%A0%E9%87%8C%E5%AD%A6%E5%8C%BA%E6%88%BF. 

*******2018-07-02 19:13:35.699688*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E4%B8%87%E7%A7%91%E5%B9%BF%E5%9C%BA%28%E5%95%86%E4%BD%8F%E6%A5%BC. 

*******2018-07-02 19:13:49.599707*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%AD%A6%E5%8C%BA%E6%88%BF. 

*******2018-07-02 20:08:04.612408*************
 本页面无数据:http://xm.58.com/ershoufang/pn8/?key=%E6%96%B0%E8%8E%B2%E8%8A%B1%E6%96%B0%E9%BE%99%E5%B1%B1%E8%8A%B1%E5%9B%AD. 

*******2018-07-02 20:17:02.158179*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%87%BA%E5%94%AE%E6%B5%B7%E8%BE%B9%E5%B0%8F%E5%8C%BA%E5%AD%A6%E5%8C%BA%E6%88%BF%E4%BB%B7%E6%A0%BC%E5%AE%9E%E6%83%A0. 

*******2018-07-02 20:34:07.145656*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%87%BA%E5%94%AE%E6%B5%85%E6%B0%B4%E6%B9%BE%E7%95%94%E5%AD%A6%E5%8C%BA%E6%88%BF. 
