
*******2018-12-03 08:25:56.320895*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E9%87%91%E9%A2%86%E5%B9%BF%E5%9C%BA. 
========2018-12-03 08:28:48.147723record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-12-03 08:38:37.098336*************
 本页面无数据:http://xm.58.com/ershoufang/pn5/?key=%E6%B5%B7%E5%B3%A1%E5%9B%BD%E9%99%85%E7%A4%BE%E5%8C%BA%E4%B8%80%E6%9C%9F. 

*******2018-12-03 08:45:29.729331*************
 本页面无数据:http://xm.58.com/ershoufang/pn4/?key=%E8%81%94%E5%8F%91%E6%AC%A3%E6%82%A6%E5%9B%AD. 

*******2018-12-03 08:48:02.069074*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E5%9B%AD%E6%9E%97%E5%AE%BF%E8%88%8D. 

*******2018-12-03 08:53:13.525816*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E7%89%B9%E6%88%BF%E5%B1%B1%E6%B0%B4%E6%96%B0%E5%BA%A7. 

*******2018-12-03 08:58:46.818600*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E6%A2%85%E9%98%B3%E8%8A%B1%E5%9B%AD. 

*******2018-12-03 09:15:41.113173*************
 本页面无数据:http://xm.58.com/ershoufang/pn6/?key=%E6%98%8E%E5%8F%91%E5%8D%8A%E5%B2%9B%E7%A5%A5%E6%B9%BEA%E5%8C%BA. 

*******2018-12-03 09:25:31.306476*************
 本页面无数据:http://xm.58.com/ershoufang/pn5/?key=%E6%96%B0%E6%99%AF%E5%9B%AD. 

               *******newFunc*******,error record by @mylog on 2018-12-03 09:41:06.956649*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 99, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-12-03 09:54:44.553031*************
 本页面无数据:http://xm.58.com/ershoufang/pn5/?key=%E4%B8%AD%E9%AA%8F%E8%93%9D%E6%B9%BE%E5%8D%8A%E5%B2%9B. 

               *******newFunc*******,error record by @mylog on 2018-12-03 10:01:02.394673*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 99, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-12-03 10:01:22.619830*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E8%81%9A%E7%A5%A5%E8%8A%B1%E5%9B%AD. 

*******2018-12-03 10:02:13.110718*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E8%8E%B2%E8%8A%B1%E5%9B%BD%E9%99%85%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

*******2018-12-03 10:08:13.836351*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E6%B3%89%E5%B7%9E%E4%B8%AD%E9%AA%8F%E5%95%86%E5%9F%8E%28%E5%95%86%E4%BD%8F%E6%A5%BC. 

*******2018-12-03 10:20:29.757443*************
 本页面无数据:http://xm.58.com/ershoufang/pn6/?key=%E6%95%85%E5%AE%AB%E8%A3%95%E6%99%AF. 

*******2018-12-03 10:22:15.702502*************
 本页面无数据:http://xm.ganji.com/fang5/o2/. 

*******2018-12-03 10:40:27.073742*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E5%BB%BA%E5%8F%91%E4%B8%AD%E5%A4%AE%E5%A4%A9%E6%82%A6. 

*******2018-12-03 10:54:32.458095*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E6%BA%90%E6%98%8C%E8%B1%AA%E5%BA%AD%E4%B8%80%E6%9C%9F. 
========2018-12-03 11:04:11.863235record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

*******2018-12-03 11:05:10.289577*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E4%B8%87%E7%A7%91%E5%B9%BF%E5%9C%BA%28%E5%95%86%E4%BD%8F%E6%A5%BC%29. 

               *******newFunc*******,error record by @mylog on 2018-12-03 11:18:23.545949*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 99, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-12-03 11:31:38.309407*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 99, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

               *******newFunc*******,error record by @mylog on 2018-12-03 11:36:55.174530*************
Traceback (most recent call last):
  File "E:\py3-craw\ToolsBox.py", line 12, in _deco
    return func(*a,**b)
  File "E:\py3-craw\ToolsBox.py", line 27, in newFunc
    back = func(*args, **args2)
  File "E:\py3-craw\MassController.py", line 99, in craw_a_page
    new_urls,new_datas = self.parser.page_parse(html_cont)      #返回解析内容
  File "E:\py3-craw\PageParser.py", line 44, in page_parse
    new_urls = self.parse_urls(soup)
  File "E:\py3-craw\LjPage.py", line 25, in parse_urls
    t_page = eval(links[0].get('page-data'))['totalPage']
IndexError: list index out of range

*******2018-12-03 11:37:50.721707*************
 本页面无数据:http://xm.58.com/ershoufang/pn4/?key=%E8%8E%B2%E8%8A%B1%E6%96%B0%E5%9F%8E%E6%B9%96%E5%9B%AD. 

*******2018-12-03 11:46:37.625844*************
 本页面无数据:http://xm.58.com/ershoufang/pn2/?key=%E9%87%91%E6%9E%97%E8%8A%B1%E5%9B%AD. 
========2018-12-03 11:51:30.375589record by outputer 
Traceback (most recent call last):
  File "E:\py3-craw\Outputer.py", line 61, in out_mysql
    data['details_url'],data['community_name'],self.now,data['from'],data['community_id']))
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "G:\Python36\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "G:\Python36\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "G:\Python36\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'spatial_arrangement' at row 1")

*******2018-12-03 12:06:50.738231*************
 本页面无数据:http://xm.58.com/ershoufang/pn4/?key=%E5%94%90%E5%BA%84. 

*******2018-12-03 12:13:33.540270*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E5%90%8C%E5%AE%89%E5%85%AC%E5%9B%AD%E9%81%93%E4%B8%80%E5%8F%B7. 

*******2018-12-03 12:18:59.973940*************
 本页面无数据:http://xm.58.com/ershoufang/pn3/?key=%E5%85%AC%E5%9B%AD%E9%81%931%E5%8F%B7. 

*******2018-12-03 12:29:40.833596*************
 本页面无数据:http://xm.58.com/ershoufang/pn9/?key=%E4%B8%AD%E5%A4%AE%E6%B9%BE%E5%8C%BA%E7%8F%8A%E7%91%9A%E6%B5%B7. 

*******2018-12-03 12:37:02.408852*************
 本页面无数据:http://xm.58.com/ershoufang/pn4/?key=%E5%8F%A4%E6%A5%BC%E5%8C%97%E9%87%8C. 

*******2018-12-03 13:38:06.059401*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E4%B8%9A%E4%B8%BB%E8%87%AA%E5%94%AE%E5%AD%A6%E5%8C%BA%E6%88%BF. 

*******2018-12-03 13:41:06.978749*************
 本页面无数据:http://xm.58.com/ershoufang/?key=%E5%A4%A7%E5%90%8C%E4%B8%AD%E5%BF%83%E5%B0%8F%E5%AD%A6%E5%AD%A6%E5%8C%BA%E6%88%BF%E9%B8%BF%E5%88%A9%E5%B0%8F%E5%8C%BA. 
